# Generated by Django 5.2.18 on 2026-10-07 14:27

import accounts.models
import accounts.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='adresse e-mail')),
                ('last_name', models.CharField(max_length=100, verbose_name='nom')),
                ('first_name', models.CharField(max_length=100, verbose_name='prénom')),
                ('role', models.CharField(choices=[('client', 'Client'), ('agent', 'Agent'), ('administrator', 'Administrateur')], default='client', max_length=20, verbose_name='rôle')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[accounts.validators.validate_phone], verbose_name='téléphone')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='date de naissance')),
                ('employee_number', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True, verbose_name="numéro d'employé")),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name="date d'inscription")),
                ('consent_date', models.DateTimeField(blank=True, null=True, verbose_name="date d'acceptation de la politique de confidentialité")),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'ordering': ['last_name', 'first_name'],
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
    ]
