# Generated by Django 5.2.18 on 2026-10-09 07:41

from django.db import migrations, models
from django.db.models import F


def mark_existing_clients_confirmed(apps, schema_editor):
    """Les clients inscrits avant cette évolution ont déjà un compte actif : ils sont confirmés."""
    User = apps.get_model("accounts", "User")
    User.objects.filter(role="client", is_active=True).update(email_confirmed_at=F("date_joined"))


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_django_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="date de confirmation de l'adresse"),
        ),
        migrations.RunPython(mark_existing_clients_confirmed, migrations.RunPython.noop),
    ]
