# Generated by Django 5.2.18 on 2026-10-09 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_phone_international_prefix'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['last_name', 'first_name', 'pk'], 'verbose_name': 'utilisateur'},
        ),
    ]
