# Generated by Django 5.2.18 on 2026-10-10 16:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_stable_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
                ('recipient', models.EmailField(blank=True, max_length=254, verbose_name='destinataire')),
                ('kind', models.CharField(choices=[('sign_up_confirmation', "Confirmation d'inscription"), ('sign_up_existing', 'Inscription avec une adresse déjà utilisée'), ('email_change_confirmation', "Confirmation d'une nouvelle adresse e-mail"), ('email_change_notice', "Alerte de changement d'adresse e-mail"), ('password_reset', 'Mot de passe oublié'), ('client_password_link', 'Lien de mot de passe envoyé par un agent'), ('agent_activation', "Activation d'un compte agent")], max_length=40, verbose_name='type')),
                ('subject', models.CharField(max_length=200, verbose_name='objet')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyé'), ('failed', 'Échec')], db_index=True, default='pending', max_length=20, verbose_name='état')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='nombre de tentatives')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='date de la dernière tentative')),
                ('last_error', models.CharField(blank=True, max_length=500, verbose_name='raison du dernier échec')),
                ('order_number', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='demande de voyage liée')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to=settings.AUTH_USER_MODEL, verbose_name='compte lié')),
            ],
            options={
                'verbose_name': "envoi d'e-mail",
                'verbose_name_plural': 'journal des e-mails',
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
