# Generated by Django 5.2.18 on 2026-10-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_delete_pending_sign_ups_before_v5'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accepts_promotional_emails',
            field=models.BooleanField(default=False, verbose_name='accepte les e-mails promotionnels'),
        ),
        migrations.AddField(
            model_name='user',
            name='promotional_emails_choice_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date du dernier changement du choix pour les e-mails promotionnels'),
        ),
    ]
