# Generated by Django 5.2.18 on 2026-10-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_order_email_kinds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='kind',
            field=models.CharField(choices=[('sign_up_confirmation', "Confirmation d'inscription"), ('sign_up_existing', 'Inscription avec une adresse déjà utilisée'), ('email_change_confirmation', "Confirmation d'une nouvelle adresse e-mail"), ('email_change_notice', "Alerte de changement d'adresse e-mail"), ('password_reset', 'Mot de passe oublié'), ('client_password_link', 'Lien de mot de passe envoyé par un agent'), ('agent_activation', "Activation d'un compte agent"), ('review_published', 'Avis publié'), ('review_refused', 'Avis refusé ou retiré'), ('review_response', "Réponse de l'agence à un avis"), ('order_placed', 'Demande de voyage reçue'), ('order_confirmed', 'Demande de voyage confirmée'), ('order_cancelled_by_client', 'Demande de voyage annulée par le client'), ('order_cancelled_by_agency', "Demande de voyage annulée par l'agence"), ('new_order_alert', 'Alerte au personnel : nouvelle demande de voyage'), ('departure_reminder', 'Rappel 7 jours avant le départ'), ('review_invitation', 'Invitation à donner un avis')], max_length=40, verbose_name='type'),
        ),
    ]
