# Generated by Django 5.2.18 on 2026-10-09 13:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_country_time_zone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='description courte')),
                ('kind', models.CharField(choices=[('percent', 'Pourcentage'), ('fixed', 'Montant fixe')], max_length=10, verbose_name='type')),
                ('value', models.DecimalField(decimal_places=2, help_text='En % pour un pourcentage, en euros pour un montant fixe.', max_digits=8, verbose_name='valeur')),
                ('scope', models.CharField(choices=[('catalog', 'Tout le catalogue'), ('countries', 'Un ou plusieurs pays'), ('destinations', 'Une ou plusieurs destinations')], default='catalog', max_length=15, verbose_name='portée')),
                ('base', models.CharField(choices=[('stay', 'Séjour (prix de la destination)'), ('activities', 'Activités'), ('total', 'Total (séjour + activités)')], default='total', max_length=15, verbose_name='assiette')),
                ('starts_on', models.DateField(verbose_name='date de début')),
                ('ends_on', models.DateField(verbose_name='date de fin')),
                ('departure_from', models.DateField(blank=True, null=True, verbose_name='départs à partir du')),
                ('departure_until', models.DateField(blank=True, null=True, verbose_name="départs jusqu'au")),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='code promo')),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='maximum de demandes au total')),
                ('max_uses_per_client', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='maximum par client')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='créée le')),
            ],
            options={
                'verbose_name': 'promotion',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='PromotionChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Création'), ('updated', 'Modification'), ('disabled', 'Désactivation')], max_length=10, verbose_name='action')),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
                ('author_name', models.CharField(max_length=210, verbose_name='auteur')),
                ('details', models.TextField(blank=True, verbose_name='détails')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='promotions.promotion')),
            ],
            options={
                'verbose_name': 'changement de promotion',
                'ordering': ['changed_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='PromotionCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.country')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.promotion')),
            ],
        ),
        migrations.AddField(
            model_name='promotion',
            name='countries',
            field=models.ManyToManyField(blank=True, through='promotions.PromotionCountry', to='catalog.country', verbose_name='pays'),
        ),
        migrations.CreateModel(
            name='PromotionDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.destination')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.promotion')),
            ],
        ),
        migrations.AddField(
            model_name='promotion',
            name='destinations',
            field=models.ManyToManyField(blank=True, through='promotions.PromotionDestination', to='catalog.destination', verbose_name='destinations'),
        ),
        migrations.AddConstraint(
            model_name='promotioncountry',
            constraint=models.UniqueConstraint(fields=('promotion', 'country'), name='promotion_country_unique'),
        ),
        migrations.AddConstraint(
            model_name='promotiondestination',
            constraint=models.UniqueConstraint(fields=('promotion', 'destination'), name='promotion_destination_unique'),
        ),
    ]
