# Generated by Django 5.2.18 on 2026-10-07 12:31

import comptes.models
import comptes.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='adresse e-mail')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100, verbose_name='prénom')),
                ('role', models.CharField(choices=[('client', 'Client'), ('agent', 'Agent'), ('administrateur', 'Administrateur')], default='client', max_length=20, verbose_name='rôle')),
                ('telephone', models.CharField(blank=True, max_length=20, validators=[comptes.validators.valider_telephone_belge], verbose_name='téléphone')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='date de naissance')),
                ('numero_employe', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True, verbose_name="numéro d'employé")),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name="accès à l'administration Django")),
                ('date_inscription', models.DateTimeField(default=django.utils.timezone.now, verbose_name="date d'inscription")),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'ordering': ['nom', 'prenom'],
            },
            managers=[
                ('objects', comptes.models.UtilisateurManager()),
            ],
        ),
    ]
