# Generated by Django 5.2.18 on 2026-10-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='date_consentement',
            field=models.DateTimeField(blank=True, null=True, verbose_name="date d'acceptation de la politique de confidentialité"),
        ),
    ]
