# Generated by Django 5.2.18 on 2026-10-07 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_date_consentement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='is_staff',
        ),
    ]
