# Generated by Django 5.2.18 on 2026-10-07 13:03

import catalogue.validators
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('continent', models.CharField(choices=[('afrique', 'Afrique'), ('amerique', 'Amérique'), ('asie', 'Asie'), ('europe', 'Europe'), ('oceanie', 'Océanie')], max_length=20)),
                ('langue_principale', models.CharField(max_length=100, verbose_name='langue principale')),
                ('monnaie', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('visa', models.CharField(choices=[('non_requis', 'Non requis'), ('e_visa', 'Visa électronique (e-visa)'), ('a_l_arrivee', "Visa à l'arrivée"), ('avant_depart', 'Visa à demander avant le départ')], default='non_requis', max_length=20, verbose_name='visa pour les Belges')),
                ('decalage_ete', models.DecimalField(decimal_places=2, help_text='En heures par rapport à la Belgique, par exemple 5.5 ou -6.', max_digits=4, validators=[catalogue.validators.valider_decalage_horaire], verbose_name='décalage horaire en été')),
                ('decalage_hiver', models.DecimalField(decimal_places=2, help_text='En heures par rapport à la Belgique, par exemple 5.5 ou -6.', max_digits=4, validators=[catalogue.validators.valider_decalage_horaire], verbose_name='décalage horaire en hiver')),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'pays',
                'ordering': ['nom'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('nom'), name='pays_nom_unique', violation_error_message='Un pays avec ce nom existe déjà.')],
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('mois_debut', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'janvier'), (2, 'février'), (3, 'mars'), (4, 'avril'), (5, 'mai'), (6, 'juin'), (7, 'juillet'), (8, 'août'), (9, 'septembre'), (10, 'octobre'), (11, 'novembre'), (12, 'décembre')], null=True, verbose_name='période idéale : de')),
                ('mois_fin', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'janvier'), (2, 'février'), (3, 'mars'), (4, 'avril'), (5, 'mai'), (6, 'juin'), (7, 'juillet'), (8, 'août'), (9, 'septembre'), (10, 'octobre'), (11, 'novembre'), (12, 'décembre')], null=True, verbose_name='période idéale : à')),
                ('prix_a_partir_de', models.DecimalField(blank=True, decimal_places=2, help_text='En euros.', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='prix indicatif « à partir de »')),
                ('photo', models.URLField(blank=True, verbose_name='adresse (URL) de la photo')),
                ('actif', models.BooleanField(default=True)),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destinations', to='catalogue.pays')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('categorie', models.CharField(choices=[('culture', 'Culture'), ('detente', 'Détente'), ('sport', 'Sport'), ('gastronomie', 'Gastronomie'), ('aventure', 'Aventure')], max_length=20, verbose_name='catégorie')),
                ('duree_minutes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='durée (en minutes)')),
                ('prix_par_personne', models.DecimalField(decimal_places=2, help_text='En euros.', max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='prix par personne')),
                ('difficulte', models.CharField(choices=[('facile', 'Facile'), ('moyen', 'Moyen'), ('difficile', 'Difficile')], max_length=20, verbose_name='niveau de difficulté')),
                ('age_minimum', models.PositiveSmallIntegerField(blank=True, help_text="Laisser vide si l'activité convient à tous les âges.", null=True, validators=[django.core.validators.MaxValueValidator(99)], verbose_name='âge minimum')),
                ('actif', models.BooleanField(default=True)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites', to='catalogue.destination')),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activites', to='catalogue.pays')),
            ],
            options={
                'verbose_name': 'activité',
                'ordering': ['nom'],
            },
        ),
    ]
