# Generated by Django 5.2.18 on 2026-10-07 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_pays_nom_cle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout")),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.activite')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'activité favorite',
                'ordering': ['-date_ajout'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('client', 'activite'), name='favori_activite_unique')],
            },
        ),
        migrations.CreateModel(
            name='FavoriDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout")),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.destination')),
            ],
            options={
                'verbose_name': 'destination favorite',
                'ordering': ['-date_ajout'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('client', 'destination'), name='favori_destination_unique')],
            },
        ),
    ]
