# Generated by Django 5.2.18 on 2026-10-07 14:27

import catalog.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('continent', models.CharField(choices=[('africa', 'Afrique'), ('america', 'Amérique'), ('asia', 'Asie'), ('europe', 'Europe'), ('oceania', 'Océanie')], max_length=20)),
                ('main_language', models.CharField(max_length=100, verbose_name='langue principale')),
                ('currency', models.CharField(max_length=100, verbose_name='monnaie')),
                ('description', models.TextField()),
                ('visa', models.CharField(choices=[('not_required', 'Non requis'), ('e_visa', 'Visa électronique (e-visa)'), ('on_arrival', "Visa à l'arrivée"), ('before_departure', 'Visa à demander avant le départ')], default='not_required', max_length=20, verbose_name='visa pour les Belges')),
                ('summer_offset', models.DecimalField(decimal_places=2, help_text='En heures par rapport à la Belgique, par exemple 5.5 ou -6.', max_digits=4, validators=[catalog.validators.validate_time_offset], verbose_name='décalage horaire en été')),
                ('winter_offset', models.DecimalField(decimal_places=2, help_text='En heures par rapport à la Belgique, par exemple 5.5 ou -6.', max_digits=4, validators=[catalog.validators.validate_time_offset], verbose_name='décalage horaire en hiver')),
                ('active', models.BooleanField(default=True, verbose_name='actif')),
                ('name_key', models.CharField(editable=False, max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'pays',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nom')),
                ('description', models.TextField()),
                ('start_month', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'janvier'), (2, 'février'), (3, 'mars'), (4, 'avril'), (5, 'mai'), (6, 'juin'), (7, 'juillet'), (8, 'août'), (9, 'septembre'), (10, 'octobre'), (11, 'novembre'), (12, 'décembre')], null=True, verbose_name='période idéale : de')),
                ('end_month', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'janvier'), (2, 'février'), (3, 'mars'), (4, 'avril'), (5, 'mai'), (6, 'juin'), (7, 'juillet'), (8, 'août'), (9, 'septembre'), (10, 'octobre'), (11, 'novembre'), (12, 'décembre')], null=True, verbose_name='période idéale : à')),
                ('price_from', models.DecimalField(blank=True, decimal_places=2, help_text='En euros.', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='prix indicatif « à partir de »')),
                ('photo', models.URLField(blank=True, verbose_name='adresse (URL) de la photo')),
                ('active', models.BooleanField(default=True, verbose_name='actif')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destinations', to='catalog.country', verbose_name='pays')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nom')),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('culture', 'Culture'), ('relaxation', 'Détente'), ('sport', 'Sport'), ('gastronomy', 'Gastronomie'), ('adventure', 'Aventure')], max_length=20, verbose_name='catégorie')),
                ('duration_minutes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='durée (en minutes)')),
                ('price_per_person', models.DecimalField(decimal_places=2, help_text='En euros.', max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='prix par personne')),
                ('difficulty', models.CharField(choices=[('easy', 'Facile'), ('medium', 'Moyen'), ('hard', 'Difficile')], max_length=20, verbose_name='niveau de difficulté')),
                ('minimum_age', models.PositiveSmallIntegerField(blank=True, help_text="Laisser vide si l'activité convient à tous les âges.", null=True, validators=[django.core.validators.MaxValueValidator(99)], verbose_name='âge minimum')),
                ('active', models.BooleanField(default=True, verbose_name='actif')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='catalog.country', verbose_name='pays')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='catalog.destination')),
            ],
            options={
                'verbose_name': 'activité',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout")),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.activity', verbose_name='activité')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'activité favorite',
                'ordering': ['-added_at'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('client', 'activity'), name='favorite_activity_unique')],
            },
        ),
        migrations.CreateModel(
            name='FavoriteDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout")),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.destination')),
            ],
            options={
                'verbose_name': 'destination favorite',
                'ordering': ['-added_at'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('client', 'destination'), name='favorite_destination_unique')],
            },
        ),
    ]
