# Generated by Django 5.2.18 on 2026-10-09 07:12

import catalog.models
import catalog.validators
import django.core.validators
from django.db import migrations, models


def clear_photo_links(apps, schema_editor):
    """Les anciens liens (https://…) ne sont pas des fichiers envoyés : on les efface."""
    Destination = apps.get_model("catalog", "Destination")
    Destination.objects.exclude(photo="").update(photo="")


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(clear_photo_links, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='destination',
            name='photo',
            field=models.ImageField(blank=True, help_text='Facultatif. JPEG, PNG ou WebP, 5 Mo maximum.', upload_to=catalog.models._photo_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'], message='Formats acceptés : JPEG, PNG ou WebP.'), catalog.validators.validate_photo_size], verbose_name='photo'),
        ),
    ]
