# Generated by Django 5.2.18 on 2026-10-09 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_destination_photo_upload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['name', 'pk'], 'verbose_name': 'activité'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name', 'pk'], 'verbose_name_plural': 'pays'},
        ),
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ['name', 'pk']},
        ),
        migrations.AlterModelOptions(
            name='favoriteactivity',
            options={'ordering': ['-added_at', '-pk'], 'verbose_name': 'activité favorite'},
        ),
        migrations.AlterModelOptions(
            name='favoritedestination',
            options={'ordering': ['-added_at', '-pk'], 'verbose_name': 'destination favorite'},
        ),
    ]
