# Generated by Django 5.2.18 on 2026-10-09 11:25

import catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_stable_ordering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='summer_offset',
        ),
        migrations.RemoveField(
            model_name='country',
            name='winter_offset',
        ),
        migrations.AddField(
            model_name='country',
            name='time_zone',
            field=models.CharField(blank=True, max_length=64, validators=[catalog.validators.validate_time_zone], verbose_name='fuseau horaire principal'),
        ),
    ]
