# Generated by Django 5.2.18 on 2026-10-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_country_time_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='passport_required',
            field=models.BooleanField(db_default=False, default=False, verbose_name='passeport obligatoire'),
        ),
    ]
