# Generated by Django 5.2.18 on 2026-10-09 08:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_destination_photo_upload'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField(verbose_name='date de départ')),
                ('return_date', models.DateField(verbose_name='date de retour')),
                ('adults', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='adultes')),
                ('children', models.PositiveSmallIntegerField(default=0, verbose_name='enfants')),
                ('remarks', models.TextField(blank=True, verbose_name='remarques')),
                ('destination_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='prix indicatif de la destination')),
                ('estimated_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='prix estimé')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('cancelled', 'Annulée')], default='pending', max_length=20, verbose_name='état')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de la demande')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='client')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='catalog.destination', verbose_name='destination')),
            ],
            options={
                'verbose_name': 'demande de voyage',
                'verbose_name_plural': 'demandes de voyage',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('cancelled', 'Annulée')], max_length=20, verbose_name='état')),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
                ('author_name', models.CharField(max_length=210, verbose_name='auteur')),
                ('reason', models.TextField(blank=True, verbose_name='motif')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='orders.order')),
            ],
            options={
                'verbose_name': "changement d'état",
                'ordering': ['changed_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='OrderActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='prix par personne au moment de la demande')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='catalog.activity')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='orders.order')),
            ],
            options={
                'verbose_name': 'activité demandée',
                'constraints': [models.UniqueConstraint(fields=('order', 'activity'), name='order_activity_unique')],
            },
        ),
    ]
