# Generated by Django 5.2.18 on 2026-10-09 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at', '-pk'], 'verbose_name': 'demande de voyage', 'verbose_name_plural': 'demandes de voyage'},
        ),
    ]
