# Generated by Django 5.2.18 on 2026-10-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_stable_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='submission_token',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
