# Generated by Django 5.2.18 on 2026-10-09 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_submission_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='remarks',
            field=models.TextField(blank=True, max_length=2000, validators=[django.core.validators.MaxLengthValidator(2000)], verbose_name='remarques'),
        ),
    ]
