# Generated by Django 5.2.18 on 2026-10-09 11:06

from django.db import migrations, models


def mark_client_changes(apps, schema_editor):
    # Jusqu'ici, une action du client se reconnaissait à son auteur « Client ».
    StatusChange = apps.get_model("orders", "StatusChange")
    StatusChange.objects.filter(author_name="Client").update(by_client=True)


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remarks_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuschange',
            name='by_client',
            field=models.BooleanField(default=False, verbose_name='par le client'),
        ),
        migrations.RunPython(mark_client_changes, migrations.RunPython.noop),
    ]
