# Generated by Django 5.2.18 on 2026-10-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_frozen_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmed_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='prix recalculé à la confirmation'),
        ),
    ]
