# Generated by Django 5.2.18 on 2026-10-09 14:01

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_confirmed_price'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmed_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='remise à la confirmation'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='remise à la demande'),
        ),
        migrations.AddField(
            model_name='order',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='promotions.promotion', verbose_name='promotion'),
        ),
        migrations.AddField(
            model_name='order',
            name='promotion_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='nom de la promotion au moment de la demande'),
        ),
    ]
