# Generated by Django 5.2.18 on 2026-10-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmed_destination_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='prix indicatif de la destination à la confirmation'),
        ),
        migrations.AddField(
            model_name='order',
            name='has_confirmed_destination_price',
            field=models.BooleanField(default=False, verbose_name='prix de la destination enregistré à la confirmation'),
        ),
    ]
