# Generated by Django 5.2.18 on 2026-10-10 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_confirmed_destination_price'),
        ('orders', '0010_fill_client_fingerprint'),
    ]

    operations = [
    ]
