# Generated by Django 5.2.18 on 2026-10-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_account_deleted_reason_internal'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='departure_reminder_sent_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name="date d'envoi du rappel avant le départ"),
        ),
        migrations.AddField(
            model_name='order',
            name='review_invitation_sent_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name="date d'envoi de l'invitation à donner un avis"),
        ),
    ]
