# Generated by Django 5.2.18 on 2026-10-09 12:10

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0007_confirmed_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='note')),
                ('title', models.CharField(max_length=100, verbose_name='titre')),
                ('comment', models.TextField(blank=True, max_length=1000, validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='commentaire')),
                ('anonymous', models.BooleanField(default=False, verbose_name='publier en tant que « Voyageur anonyme »')),
                ('status', models.CharField(choices=[('pending', 'En attente de validation'), ('published', 'Publié'), ('refused', 'Refusé')], default='pending', max_length=20, verbose_name='état')),
                ('refusal_reason', models.CharField(blank=True, choices=[('abusive', 'Langage injurieux'), ('off_topic', 'Hors sujet'), ('personal_data', 'Contient des coordonnées personnelles'), ('trip_cancelled', 'Voyage annulé'), ('other', 'Autre')], max_length=20, verbose_name='motif du refus')),
                ('refusal_details', models.TextField(blank=True, max_length=500, validators=[django.core.validators.MaxLengthValidator(500)], verbose_name='précision sur le motif')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name="date de l'avis")),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='date de publication')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='review', to='orders.order', verbose_name='demande de voyage')),
            ],
            options={
                'verbose_name': 'avis',
                'verbose_name_plural': 'avis',
                'ordering': ['-created_at', '-pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='review_rating_1_to_5')],
            },
        ),
    ]
