# Generated by Django 5.2.18 on 2026-10-09 12:20

import django.utils.timezone
from django.db import migrations, models
from django.db.models import F


def use_creation_date(apps, schema_editor):
    # Avis existants : envoyés en validation à leur création.
    apps.get_model("reviews", "Review").objects.update(submitted_at=F("created_at"))


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='envoyé en validation le'),
        ),
        migrations.RunPython(use_creation_date, migrations.RunPython.noop),
    ]
