# Generated by Django 5.2.18 on 2026-10-09 12:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_submitted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_first_name', models.CharField(max_length=100, verbose_name="prénom de l'auteur")),
                ('text', models.TextField(max_length=1000, validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='réponse')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de la réponse')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='dernière modification')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='reviews.review', verbose_name='avis')),
            ],
            options={
                'verbose_name': "réponse de l'agence",
                'verbose_name_plural': "réponses de l'agence",
            },
        ),
    ]
