# Generated by Django 5.2.18 on 2026-10-09 13:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def sign_existing_reviews(apps, schema_editor):
    # Avis existants : signature figée à partir du nom actuel du client.
    Review = apps.get_model("reviews", "Review")
    for review in Review.objects.select_related("order__client").filter(order__client__isnull=False):
        client = review.order.client
        initial = f" {client.last_name[:1].upper()}." if client.last_name else ""
        review.signature = f"{client.first_name}{initial}"
        review.save(update_fields=["signature"])


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_confirmed_price'),
        ('reviews', '0003_agency_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='signature',
            field=models.CharField(blank=True, max_length=120, verbose_name='signature publique'),
        ),
        migrations.AddField(
            model_name='review',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='version'),
        ),
        migrations.CreateModel(
            name='ReviewWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdrawn_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='retiré le')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_withdrawal', to='orders.order')),
            ],
            options={
                'verbose_name': 'avis retiré',
                'verbose_name_plural': 'avis retirés',
            },
        ),
        migrations.RunPython(sign_existing_reviews, migrations.RunPython.noop),
    ]
